import React, { useEffect, useState } from "react";
import { authenticateCeramic } from "../utils";
import { useCeramicContext } from "../context";

const AuthPrompt = () => {
  const [isVisible, setIsVisible] = useState(true);
  const clients = useCeramicContext();
  const { ceramic, composeClient } = clients;
  const isLogged = () => {
    return (localStorage.getItem("logged_in") == "true");
  };

  useEffect(()=>{
    if(typeof window !== 'undefined'&&isVisible&&isLogged()){
      setIsVisible(false)
    }
  },[])

  
  const handleOpen = () => {
    if (localStorage.getItem("logged_in")) {
      setIsVisible(true);
    } else {
      setIsVisible(false);
    }
  };

  const handleKeyDid = () => {
    localStorage.setItem("ceramic:auth_type", "key");
    authenticateCeramic(ceramic, composeClient);
    setIsVisible(false);
  };

  const handleEthPkh = () => {
    localStorage.setItem("ceramic:auth_type", "eth");
    authenticateCeramic(ceramic, composeClient);
    setIsVisible(false);
  };

  return (
    <div>
      {isVisible && (
        <div className='popup'>
          <div className='popup-content'>
            <h2>Authenticate</h2>
            <div className="buttonsStuff">
            <span>
              <button onClick={handleEthPkh}>Eth DID PKH</button>
            </span>
            </div>
            <div className="loginButtonSupportText">
              <br />
              <strong>Ethereum DID PKH:</strong> A DID generated by your wallet
              <br />
              (in simpler terms: login with MetaMask).
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AuthPrompt;
